default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: billete_development

test:
  <<: *default
  database: billete_test

production:
  primary: &primary_production
    <<: *default
    database: billete_production
    <% if ENV["DB_HOST"] && !ENV["DB_HOST"].empty? %>
    host: <%= ENV["DB_HOST"] %>
    <% end %>
    <% if ENV["DB_USERNAME"] && !ENV["DB_USERNAME"].empty? %>
    username: <%= ENV["DB_USERNAME"] %>
    <% end %>
    <% if ENV["DB_PASSWORD"] && !ENV["DB_PASSWORD"].empty? %>
    password: <%= ENV["DB_PASSWORD"] %>
    <% end %>
  cache:
    <<: *primary_production
    database: billete_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: billete_queue
    migrations_paths: db/queue_migrate
